/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.appointmentregistration.view;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Roxana
 */
public class GUIAddAppointment extends javax.swing.JPanel {

    /**
     * Creates new form GUIADDAPPOINTMENT
     */
    public GUIAddAppointment() {
        initComponents();
    }
    
    //Este comobox contine todas la areas que va a ver en nuestra clinica
    public void setComboArea(){
        this.cbAreas.setModel(new DefaultComboBoxModel<>(new String []{"Selected Option","Internal Medicine","Pediatrics","Surgery", "Dermatology", "Ophthalmology","Odontology","Emergencies","Neurology"}));
    }
    
    //Este metodo obtiene lo que se selecciona en el combo
    public String getComboArea(){
        return this.cbAreas.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTimeAndDate = new javax.swing.JTable();
        cbAreas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbAppointments = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbIdentificationCard = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Register appointment:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calisto MT", 0, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        btnExit.setText("Exit");
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 96, 60));

        tbTimeAndDate.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        tbTimeAndDate.setForeground(new java.awt.Color(255, 255, 255));
        tbTimeAndDate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ));
        jScrollPane1.setViewportView(tbTimeAndDate);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 380, 240));

        cbAreas.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        cbAreas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbAreas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 152, 31));

        jLabel2.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Area:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 140, -1));

        jLabel3.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel3.setText("Appointment");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        cbAppointments.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        cbAppointments.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbAppointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 152, 30));

        jLabel4.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" Time and date of appointments:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 350, -1));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel1.setText("Identification Card:\n");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lbIdentificationCard.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        lbIdentificationCard.setText("jLabel5");
        jPanel1.add(lbIdentificationCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 450));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox<String> cbAppointments;
    private javax.swing.JComboBox<String> cbAreas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbIdentificationCard;
    private javax.swing.JTable tbTimeAndDate;
    // End of variables declaration//GEN-END:variables
}
